# 𝐀𝐬𝐬𝐨𝐜𝐢𝐚𝐭𝐢𝐨𝐧 𝐑𝐮𝐥𝐞 𝐋𝐞𝐚𝐫𝐧𝐢𝐧𝐠 :

In [1]:
# Import library :
import pandas as pd
from mlxtend.frequent_patterns import apriori, association_rules

In [2]:
# Example Data: list of transaction..
data = {
    "TransactionId" : [1, 1, 1, 2, 2, 3, 3, 3, 4, 4, 4, 4],
    "Item" : ["Milk", "Bread", "Butter", "Bread", "Butter", "Milk", "Bread",
             "Eggs", "Milk", "Bread", "Butter", "Eggs"] 
}

In [3]:
data

{'TransactionId': [1, 1, 1, 2, 2, 3, 3, 3, 4, 4, 4, 4],
 'Item': ['Milk',
  'Bread',
  'Butter',
  'Bread',
  'Butter',
  'Milk',
  'Bread',
  'Eggs',
  'Milk',
  'Bread',
  'Butter',
  'Eggs']}

In [4]:
# Create Dataframe :
df = pd.DataFrame(data)
df = df.groupby(['TransactionId', 'Item'])['Item'].count().unstack().reset_index().fillna(0).set_index('TransactionId')
df = df.applymap(lambda x: 1 if x > 0 else 0)

In [5]:
# Applying the apriori algorithm:
frequent_itemsets = apriori(df, min_support=0.5, use_colnames=True)

C:\Users\kunal\anaconda3\Lib\site-packages\mlxtend\frequent_patterns\fpcommon.py:109: DeprecationWarning: DataFrames with non-bool types result in worse computationalperformance and their support might be discontinued in the future.Please use a DataFrame with bool type
  warnings.warn(

In [6]:
frequent_itemsets

    support               itemsets
0      1.00                (Bread)
1      0.75               (Butter)
2      0.50                 (Eggs)
3      0.75                 (Milk)
4      0.75        (Butter, Bread)
5      0.50          (Eggs, Bread)
6      0.75          (Bread, Milk)
7      0.50         (Butter, Milk)
8      0.50           (Eggs, Milk)
9      0.50  (Butter, Bread, Milk)
10     0.50    (Eggs, Bread, Milk)

In [7]:
# Generating association rules:
rules = association_rules(frequent_itemsets, metric="confidence", min_threshold=0.7)
rules

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction,zhangs_metric
0,(Butter),(Bread),0.75,1.00,0.75,1.00,1.000000,0.000,inf,0.0
1,(Bread),(Butter),1.00,0.75,0.75,0.75,1.000000,0.000,1.0,0.0
2,(Eggs),(Bread),0.50,1.00,0.50,1.00,1.000000,0.000,inf,0.0
3,(Bread),(Milk),1.00,0.75,0.75,0.75,1.000000,0.000,1.0,0.0
4,(Milk),(Bread),0.75,1.00,0.75,1.00,1.000000,0.000,inf,0.0
5,(Eggs),(Milk),0.50,0.75,0.50,1.00,1.333333,0.125,inf,0.5
6,"(Butter, Milk)",(Bread),0.50,1.00,0.50,1.00,1.000000,0.000,inf,0.0
7,"(Eggs, Bread)",(Milk),0.50,0.75,0.50,1.00,1.333333,0.125,inf,0.5
8,"(Eggs, Milk)",(Bread),0.50,1.00,0.50,1.00,1.000000,0.000,inf,0.0
9,(Eggs),"(Bread, Milk)",0.50,0.75,0.50,1.00,1.333333,0.125,inf,0.5

In [8]:
# print association rules:
print("𝐅𝐫𝐞𝐪𝐮𝐞𝐧𝐭 𝐈𝐭𝐞𝐦𝐬𝐞𝐭𝐬:")
print(frequent_itemsets)
print("\n𝐀𝐬𝐬𝐨𝐜𝐢𝐚𝐭𝐢𝐨𝐧 𝐑𝐮𝐥𝐞𝐬:")
print(rules)

𝐅𝐫𝐞𝐪𝐮𝐞𝐧𝐭 𝐈𝐭𝐞𝐦𝐬𝐞𝐭𝐬:
    support               itemsets
0      1.00                (Bread)
1      0.75               (Butter)
2      0.50                 (Eggs)
3      0.75                 (Milk)
4      0.75        (Butter, Bread)
5      0.50          (Eggs, Bread)
6      0.75          (Bread, Milk)
7      0.50         (Butter, Milk)
8      0.50           (Eggs, Milk)
9      0.50  (Butter, Bread, Milk)
10     0.50    (Eggs, Bread, Milk)

𝐀𝐬𝐬𝐨𝐜𝐢𝐚𝐭𝐢𝐨𝐧 𝐑𝐮𝐥𝐞𝐬:
      antecedents    consequents  antecedent support  consequent support  \
0        (Butter)        (Bread)                0.75                1.00
1         (Bread)       (Butter)                1.00                0.75
2          (Eggs)        (Bread)                0.50                1.00
3         (Bread)         (Milk)                1.00                0.75
4          (Milk)        (Bread)                0.75                1.00
5          (Eggs)         (Milk)                0.50                0.75
6  (Butter, Milk)        (Bread)                0.50                1.00
7   (Eggs, Bread)         (Milk)                0.50                0.75
8    (Eggs, Milk)        (Bread)                0.50                1.00
9          (Eggs)  (Bread, Milk)                0.50                0.75

   support  confidence      lift  leverage  conviction  zhangs_metric
0     0.75        1.00  1.000000     0.000         inf            0.0
1     0.75        0.75  1.000000     0.000         1.0            0.0
2     0.50        1.00  1.000000     0.000         inf            0.0
3     0.75        0.75  1.000000     0.000         1.0            0.0
4     0.75        1.00  1.000000     0.000         inf            0.0
5     0.50        1.00  1.333333     0.125         inf            0.5
6     0.50        1.00  1.000000     0.000         inf            0.0
7     0.50        1.00  1.333333     0.125         inf            0.5
8     0.50        1.00  1.000000     0.000         inf            0.0
9     0.50        1.00  1.333333     0.125         inf            0.5

𝐂𝐨𝐧𝐜𝐞𝐩𝐭: 
           Association rule learning is a rule-based machine learning method used to discover interesting relations between variables in large databases. It is widely used in market basket analysis to identify sets of products that frequently co-occur in transactions. The main goal is to find strong rules discovered in databases using some measures of interestingness.

--> 𝐊𝐞𝐲 𝐓𝐞𝐫𝐦𝐬 :-
    
- 𝐒𝐮𝐩𝐩𝐨𝐫𝐭: The proportion of transactions in the dataset that contain a particular itemset.
    
- 𝐂𝐨𝐧𝐟𝐢𝐝𝐞𝐧𝐜𝐞: The likelihood that a transaction containing an itemset A also contains an itemset B.
    
- 𝐋𝐢𝐟𝐭: The ratio of the observed support to that expected if A and B  were independent.

==> 𝐀𝐥𝐠𝐨𝐫𝐢𝐭𝐡𝐦 :
    
The most common algorithm for association rule learning is the Apriori algorithm. It operates in two steps:

- 𝟏. 𝐅𝐫𝐞𝐪𝐮𝐞𝐧𝐭 𝐈𝐭𝐞𝐦𝐬𝐞𝐭 𝐆𝐞𝐧𝐞𝐫𝐚𝐭𝐢𝐨𝐧: Identify all itemsets whose support is greater than or equal to a specified minimum support threshold.
- 𝟐. 𝐑𝐮𝐥𝐞 𝐆𝐞𝐧𝐞𝐫𝐚𝐭𝐢𝐨𝐧: From the frequent itemsets, generate high-confidence rules where confidence is greater than or equal to a specified minimum confidence threshold.